import pandas as pd
# =====generated by AI=====
import matplotlib
matplotlib.use('Agg')
import folium
from folium.plugins import HeatMap
# =========================
import matplotlib.pyplot as plt

from src.analysis import (resolution_summary, 
                          top10_complaints, 
                          borough_counts, 
                          agency_resolution_time,
                          complaint_resolution_time,
                          top_complaints_by_borough,
                          agency_complaint_counts)

# Purpose: Draws a horizontal bar chart of the top complaint types.
# Parameters: complaints (pd.Series) – indexed by complaint type, values = counts.
# Output: Horizontal bar chart 
def plot_top_complaints(complaints: pd.Series) -> None:

    plt.figure(figsize=(10,6))

    complaints.sort_values().plot.barh(
        color="steelblue"
    )

    plt.xlabel("Number of Complaints")
    plt.ylabel("Complaint Type")
    plt.title("Top Complaint Types")
    plt.tight_layout()
    plt.savefig("figures/top_complaints.png")
    plt.close()


# Purpose: Draws a pie chart of complaint distribution by borough.
# Parameters: borough_counts (pd.Series) – indexed by borough.
# Output: Pie chart with percentage labels.
def plot_borough_distribution(borough_counts: pd.Series) -> None:

    plt.figure(figsize=(8,8))

    borough_counts.plot.pie(
        autopct="%1.1f%%"
    )

    plt.ylabel("")
    plt.title("Complaint Distribution by Borough")
    plt.tight_layout()
    plt.savefig("figures/borough_distribution.png")
    plt.close()


# Purpose: Draws a horizontal bar chart of average resolution time per agency.
# Parameters: agency_times (pd.Series) – indexed by agency
# Output: Bar chart
def plot_agency_resolution(agency_times: pd.Series) -> None:

    plt.figure(figsize=(10,6))

    agency_times.plot.barh(
        color="orange"
    )

    plt.xlabel("Average Resolution Time (Hours)")
    plt.ylabel("Agency")
    plt.title("Average Resolution Time by Agency")
    plt.tight_layout()
    plt.savefig("figures/avg_agency_resolution_time.png")
    plt.close()


# Purpose: Draws a histogram of resolution times.
# Parameters: hours (pd.Series) – values in hours.
# Output: Histogram with 50 bins
def plot_resolution_histogram(hours: pd.Series) -> None:

    plt.figure(figsize=(10,6))

    plt.hist(
        hours,
        bins=50,
        edgecolor="black"
    )

    plt.xlabel("Resolution Time (Hours)")
    plt.ylabel("Count")
    plt.title("Distribution of Resolution Times")
    plt.tight_layout()
    plt.savefig("figures/agency_resolution_time.png")
    plt.close()


# Purpose: Draws a horizontal bar chart of total complaint counts per agency.
# Parameters: agency_counts (pd.Series) - indexed by agency, values = counts.
# Output: Bar chart
def plot_agency_complaint_counts(agency_counts):
    plt.figure(figsize=(10,6))
    agency_counts.sort_values().plot.barh(color="purple")
    plt.xlabel("Number of Complaints")
    plt.ylabel("Agency")
    plt.title("Total Complaints by Agency")
    plt.tight_layout()
    plt.savefig("figures/agency_complaint_counts.png")
    plt.close()


# Purpose: Draws a stacked bar chart of top complaint types per borough.
# Parameters: df_borough (pd.DataFrame) - contains 'borough', 'complaint_type', 'count'.
# Output: Stacked bar chart
def plot_top_complaints_by_borough(df_borough):
    pivot_df = df_borough.pivot(index='borough', columns='complaint_type', values='count').fillna(0)
    
    plt.figure(figsize=(12,8))

    pivot_df.plot(kind="bar", stacked=True, ax=plt.gca(), colormap="tab20")
    plt.xlabel("Borough")
    plt.ylabel("Number of Complaints")
    plt.title("Top Complaint Types by Borough")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig("figures/top_complaints_by_borough.png")
    plt.close()

#========================= AI generated =============================
# Purpose: Draws a 2D histogram (heatmap) of complaint density using longitude and latitude.
# Parameters: DataFrame df with longitude and latitude columns.
# Output: a hist2d plot
def plot_heatmap(df):
    clean_df = (df[["latitude", "longitude"]].dropna())
    m = folium.Map(
        location=[40.7128, -74.0060],
        zoom_start=10
    )
    HeatMap(
        clean_df.values.tolist(),
        radius=10,
        blur=15
    ).add_to(m)
    m.save(
        "figures/request_heatmap.html"
    )
# ===================================================================

# Purpose: gathering all draw-image functions
# parameter: DataFrame df
# Ouput: seven images
def plot_images(df):
    plot_top_complaints(top10_complaints(df))
    plot_borough_distribution(borough_counts(df))
    plot_agency_resolution(agency_resolution_time(df))
    plot_resolution_histogram(complaint_resolution_time(df))
    plot_agency_complaint_counts(agency_complaint_counts(df))
    plot_top_complaints_by_borough(top_complaints_by_borough(df))
    plot_heatmap(df)